"""
Interface Contract — Phase 1 Workflow Foundation
OpenVINO Physical AI for Thermal Measurement Automation

This file is the single source of truth for the data that crosses module
boundaries in Phase 1. The OpenVINO/YOLO-seg perception pipeline and
PyBullet control layer should both import these types instead of passing
raw dicts/tuples around, so modules can be developed in parallel and
swapped out independently later.

Pipeline:
    thermal image
        -> [OpenVINO perception]   -> HotspotDetection (pixel frame)
        -> [coordinate transform]  -> RobotTarget      (robot base frame)
        -> [PyBullet action layer] -> ActionResult     (validation feedback)
"""

from dataclasses import dataclass, field
from enum import Enum
from time import time
from typing import Optional


# ---------------------------------------------------------------------------
# Shared enums
# ---------------------------------------------------------------------------

class CoordinateFrame(str, Enum):
    PIXEL = "pixel"            # raw (x, y) in the source image
    CAMERA = "camera"          # 3D point in camera optical frame
    ROBOT_BASE = "robot_base"  # 3D point in the robot arm's base frame


class ActionType(str, Enum):
    MOVE = "move"
    PICK = "pick"
    PLACE = "place"


class ActionStatus(str, Enum):
    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# 1. Perception module output
# ---------------------------------------------------------------------------

@dataclass
class HotspotDetection:
    """One detected thermal hotspot from the OpenVINO/YOLO-seg pipeline."""
    hotspot_id: str                 # stable id within a single frame, e.g. "h0"
    x: float                        # coordinate value 1 (pixel col, or camera-frame X)
    y: float                        # coordinate value 2 (pixel row, or camera-frame Y)
    z: Optional[float] = None       # camera-frame depth, if available; None for pixel frame
    confidence: float = 0.0         # segmentation/detection confidence, 0-1
    coordinate_frame: CoordinateFrame = CoordinateFrame.PIXEL
    image_width: Optional[int] = None
    image_height: Optional[int] = None
    timestamp: float = field(default_factory=time)

    def validate(self) -> None:
        assert 0.0 <= self.confidence <= 1.0, "confidence must be in [0, 1]"
        if self.coordinate_frame == CoordinateFrame.PIXEL:
            assert self.image_width and self.image_height, \
                "pixel-frame detections must include image_width/image_height"


# ---------------------------------------------------------------------------
# 2. Coordinate transform output
# ---------------------------------------------------------------------------

@dataclass
class RobotTarget:
    """A hotspot converted into a pose the robot arm can act on."""
    target_id: str                  # usually same as source hotspot_id
    source_hotspot_id: str
    x: float                        # robot base frame, meters
    y: float
    z: float
    coordinate_frame: CoordinateFrame = CoordinateFrame.ROBOT_BASE
    approach_vector: tuple = (0.0, 0.0, -1.0)  # default: approach from above
    timestamp: float = field(default_factory=time)

    def validate(self) -> None:
        assert self.coordinate_frame == CoordinateFrame.ROBOT_BASE, \
            "RobotTarget must always be in robot_base frame before reaching the action module"


# ---------------------------------------------------------------------------
# 3. Action command generated by planning/transform
# ---------------------------------------------------------------------------

@dataclass
class ActionCommand:
    action_type: ActionType
    target: RobotTarget
    task_id: str = ""

    def __post_init__(self):
        if not self.task_id:
            self.task_id = f"{self.action_type.value}-{self.target.target_id}"


# ---------------------------------------------------------------------------
# 4. Action execution feedback
# ---------------------------------------------------------------------------

@dataclass
class ActionResult:
    task_id: str
    status: ActionStatus
    achieved_x: Optional[float] = None
    achieved_y: Optional[float] = None
    achieved_z: Optional[float] = None
    error_mm: Optional[float] = None   # distance between target and achieved pose
    message: str = ""
    timestamp: float = field(default_factory=time)
